create TABLE players (
    id_player INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tell VARCHAR(15) NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    level INT NOT NULL DEFAULT 0,
    xp INT NOT NULL DEFAULT 0,
    dinheiro NUMERIC(10,2) NOT NULL DEFAULT 0
)